language: python
python:
  - 2.7
env:
  matrix:
  - TEST_SPHINX="yes"
before_install:
  - sudo apt-get update
  - if [[ "${TEST_SPHINX}" == "yes" ]]; then
      sudo apt-get install --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-latex-recommended dvipng;
      pip install "sphinx==1.2b3";
    fi
script:
  - bin/test_travis.sh
notifications:
  email: false
